config/routes.rb
Healthtracker::Application.routes.draw do
  get "pages/about"

  get "scores/dashboard"

  devise_for :users

  root :to => "scores#dashboard"
  
  match '/dashboard' => 'scores#dashboard'
  match '/about' => 'pages#about'

  resources :days

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :user
  
  def score
    score = 0
    score = score + self.food_veg_actual
    score = score + self.food_junk_actual
    score = score + self.hours_sleep_actual
    score = score + self.exercise_actual
    score = score + self.smoke_actual
    score = score + self.drinks_actual
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /days
  # GET /days.json
  def index
    @days = Day.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @days }
    end
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @day = Day.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/new
  # GET /days/new.json
  def new
    @day = Day.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(params[:day])
    logger.debug "date is " + params[:day][:date] 
    @day.date = params[:day][:date]
    @day.user_id = current_user.id
    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render json: @day, status: :created, location: @day }
      else
        format.html { render action: "new" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /days/1
  # PUT /days/1.json
  def update
    @day = Day.find(params[:id])
    @day.user_id = current_user.id
    respond_to do |format|
      if @day.update_attributes(params[:day])
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day = Day.find(params[:id])
    @day.destroy

    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def dashboard
    
    @maximum_score = 12.0
    
    @one_week_score = get_score_for_period(1) 
    @two_week_score = get_score_for_period(2) 
    @four_week_score = get_score_for_period(4) 
    
    
    
  end
  
  private
  
  def get_score_for_period(period_in_weeks)
    if current_user
      the_records = current_user.days.find(:all, :conditions => ['created_at > ?', period_in_weeks.week.ago])
    
      @the_score = 0
      count = 0
      
      the_records.each do |rec|
        @the_score = @the_score + rec.score
        count = count + 1  
      end 
      
      @the_score / Float(count)
      
    else
      
      0.0
      
    end
    
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
  
  def get_box_color(score)
    threshold = 12
    
    if score >= (threshold/ 2)
      'green'
    else
      'red'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/days/_form.html.erb
<div class="control-group">
   <%= f.label :date, t("activerecord.attributes.day.date", :default => "Date"), :class => 'control-label' %>
  <div class="input">
    <%= f.datepicker :date, :class => 'date_field', :dateFormat => 'dd-mm-yy'  %>
  </div>
</div>

<div class="control-group">
   <%= f.label :food_veg_actual, t("activerecord.attributes.day.food_veg_actual", :default => "Vegtables Eaten"), :class => 'control-label'  %>
  <div class="input">
    
    <%= f.select :food_veg_actual, options_for_select([["A Lot", "2"], 
                  ["Some", "1"], ["None" ,"-2"]], [(@day.food_veg_actual || '1')]
                 ), {:multiple => true} %>
  </div>
</div>

<div class="control-group">
   <%= f.label :food_junk_actual, t("activerecord.attributes.day.food_junk_actual", :default => "Junk Food Eaten"), :class => 'control-label' %>
  <div class="input">
     <%= f.select :food_junk_actual, options_for_select([["A Lot", "-2"], 
                  ["Some", "-1"], ["None" ,"2"]], [(@day.food_junk_actual || '-1')]
                 ), {:multiple => true} %>
  </div>
</div>

<div class="control-group">
   <%= f.label :hours_sleep_actual, t("activerecord.attributes.day.hours_sleep_actual", :default => "Amount of sleep"), :class => 'control-label' %>
  <div class="input">
    <%= f.select :hours_sleep_actual, options_for_select([["Not Enough" ,"-2"],["Enough but only just", "1"], 
                  ["Spot On", "2"]], [(@day.hours_sleep_actual || '1')]
                 ), {:multiple => true} %>
  </div>
</div>

<div class="control-group">
   <%= f.label :exercise_actual, t("activerecord.attributes.day.exercise_actual", :default => "Exercise done"), :class => 'control-label' %>
  <div class="input">
    <%= f.select :exercise_actual, options_for_select([["None" ,"0"], 
                  ["Some", "1"], ["A Lot", "2"]], [(@day.exercise_actual || '1')]
                 ), {:multiple => true} %>
  </div>
</div>

<div class="control-group">
   <%= f.label :smoke_actual, t("activerecord.attributes.day.smoke_actual", :default => "Cigarettes Smoked"), :class => 'control-label' %>
  <div class="input">
    <%= f.select :smoke_actual, options_for_select([["None", "2"], 
                  ["The Usual", "-1"], ["A Lot" ,"-2"]], [(@day.smoke_actual || '2')]
                 ), {:multiple => true} %>
  </div>
</div>

<div class="control-group">
   <%= f.label :drinks_actual, t("activerecord.attributes.day.drinks_actual", :default => "Alcoholic Drinks"), :class => 'control-label' %>
  <div class="input">
    <%= f.select :drinks_actual, options_for_select([["Just Right", "2"], 
                  ["A bit too much", "-1"], ["Way too many" ,"-2"]], [(@day.drinks_actual || '2')]
                 ), {:multiple => true} %>
  </div>
</div>
<div class="form-actions">
  <button class="btn primary" type="submit">Save</button> or
	<%= link_to "Cancel", days_path %>
</div>

app/views/days/edit.html.erb
<%= form_for @day, :url => day_path(@day), :html => { :class => "edit_day form_inline", :id => "edit_day" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/days/index.html.erb
<h1>Days</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>Date</th>
    <th>Score</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @days.each do |day| -%>
   <tr>
    	<td><%= day.date %></td>
        <td><%= day.score %></td>
    <td>
      <%= link_to "Show", day_path(day) %>
      <%= link_to "Edit", edit_day_path(day) %>
      <%= link_to "Destroy", day_path(day), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>

<%= link_to "New", new_day_path, :class => 'btn btn-primary' %>

app/views/days/new.html.erb
<%= form_for @day, :url => days_path, :html => { :class => 'form_inline' } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/days/show.html.erb
<h1><%= @day.date %></h1>
<table id="score_breakdown">
	<tr>
		<td>
			<strong>Category</strong>
		</td>
		<td  class="score_column">
			<strong>Score</strong>
		</td>
	</tr>
	<tr>
		<td>	
			Fruit and Veg
		</td>
		<td class="score_column">
			<%= @day.food_veg_actual %></p>
		</td>
	</tr>
	<tr>
		<td>	
			Junk Food
		</td>
		<td class="score_column">
			<%= @day.food_junk_actual  %></p>
		</td>
	</tr>
	<tr>
		<td>	
			Sleep
		</td>
		<td class="score_column">
			<%= @day.hours_sleep_actual  %></p>
		</td>
	</tr>
	<tr>
		<td>	
			Exercise
		</td>
		<td class="score_column">
			<%= @day.exercise_actual  %></p>
		</td>
	</tr>
	<tr>
		<td>	
			Smoking
		</td>
		<td class="score_column">
			<%= @day.smoke_actual  %></p>
		</td>
	</tr>
	<tr>
		<td>	
			Drinking
		</td>
		<td class="score_column">
			<%= @day.drinks_actual  %></p>
		</td>
	</tr>
	<tr>
		<td>	
			<strong>Total</strong>
		</td>
		<td class="score_column">
			<strong><%= @day.score  %></p></strong>
		</td>
	</tr>
</table>


<div class="form-actions">
<%= link_to "Back", days_path, :class => 'btn'  %>
<%= link_to "Edit", edit_day_path(@day), :class => 'btn' %>
<%= link_to "Delete", day_path(@day), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Simple Health Tracker</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
     <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/">simple health tracker</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li><%= link_to "dashboard", "/dashboard"  %></li>
                <li><%= link_to "new entry", new_day_path  %></li>
                <li><%= link_to "about", "/about"  %></li>
                <% if !user_signed_in? %>
                	<li><%= link_to "login", "/users/sign_in"  %></li>
                <% else %>
             		<li><%= link_to("logout", destroy_user_session_path, :method => :delete) %></li>
                <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>stuff to do</h3>
                 <ul class="nav nav-list">
                    <li><%= link_to "goto Dashboard", "/dashboard"  %></li>
                    <li><%= link_to "enter info", "/days/new"  %></li>
                    <li><%= link_to "view all days", "/days"  %></li>
                    <li><%= link_to "edit profile", edit_user_registration_path  %></li>
                    <% if !user_signed_in? %>
                      <li><%= link_to "login", "/users/sign_in"  %></li>
                    <% else %>
                      <li><%= link_to("logout", destroy_user_session_path, :method => :delete) %></li>
                    <% end %>
                </ul>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy; ben dixon 2012 | <a href="http://www.twitter.com/talkingquickly">@talkingquickly</a> | join <%= number_with_delimiter(rand(1500000), :delimiter => ',').to_s %> others tracking health simply</p>
      </footer>

    </div> <!-- /container -->

   

  </body>
</html>

app/views/pages/about.html.erb
<div id="about_page">
	<h1>About</h1>
	<h2>What is Simple Health Tracker</h2>
	<p>It's a really really simple health tracker. There are lots of Apps and the like out there 
		for tracking bits of your health in detail, sleep trackers, diet trackers, exercise trackers
		and drinking trackers; which are great but they take a lot of time to fill in.</p>
	<p>This tool is for keeping a rough track of whether or not this was a good day/ week / month. It's 
		totally subjective, there are no numbers, you know roughly whether you got enough sleep last night,
		whether you did some exercise and whether you had too much to drink. This keeps track of that.</p>
	<h2>Does a good score mean I'm healthy</h2>
	<p>No - a good score just means you've assessed yourself as doing quite well. If your definition of
		"A lot of vegetables" is 1 a day, you'll get a lot of good scores but you probably won't be that healthy(!)</p>
	<h2>How do I get started?</h2>
	<p><a href="/users/sign_up">"Sign up here!</a></p>
</div>

app/views/scores/dashboard.html.erb
<h1>scorecard</h1>
<div id="main_scores_wrap">
	<div class="main_score_box <%= get_box_color(@one_week_score) %>">
		<div class="main_score_box_score">
			<%= number_with_precision(@one_week_score, :precision => 0)  %> / <%= number_with_precision(@maximum_score, :precision => 0) %>
		</div>
		<div class="main_score_box_title">
			Last Week
		</div>
	</div>
	<div class="main_score_box <%= get_box_color(@two_week_score) %>">
		<div class="main_score_box_score">
			<%= number_with_precision(@two_week_score, :precision => 0)  %> / <%= number_with_precision(@maximum_score, :precision => 0) %>
		</div>
		<div class="main_score_box_title">
			Last 2 Weeks
		</div>
	</div>
	<div class="main_score_box <%= get_box_color(@four_week_score) %>">
		<div class="main_score_box_score">
			<%= number_with_precision(@four_week_score, :precision => 0)  %> / <%= number_with_precision(@maximum_score, :precision => 0) %>
		</div>
		<div class="main_score_box_title">
			Last 4 Weeks
		</div>
	</div>
</div>
<div id="explanation">
	<h2>what does this mean?</h2>
	<p>Each box shows your average score for the period over the maximum score possible (<%= @maximum_score %>)</p>
	<p>The box goes green when you get above half of the maximum (six).</p>
	<p>For more on what a "green" score means check the about page</p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :food_veg_target %><br />
    <%= f.number_field :food_veg_target %>
  </div>
  <div class="field">
    <%= f.label :food_junk_target %><br />
    <%= f.number_field :food_junk_target %>
  </div>
  <div class="field">
    <%= f.label :hours_sleep_target %><br />
    <%= f.text_field :hours_sleep_target %>
  </div>
  <div class="field">
    <%= f.label :weekly_exercise_target %><br />
    <%= f.number_field :weekly_exercise_target %>
  </div>
  <div class="field">
    <%= f.label :smoke_total %><br />
    <%= f.text_field :smoke_total %>
  </div>
  <div class="field">
    <%= f.label :weekly_drinks_target %><br />
    <%= f.number_field :weekly_drinks_target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Food veg target</th>
    <th>Food junk target</th>
    <th>Hours sleep target</th>
    <th>Weekly exercise target</th>
    <th>Smoke total</th>
    <th>Weekly drinks target</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.food_veg_target %></td>
    <td><%= user.food_junk_target %></td>
    <td><%= user.hours_sleep_target %></td>
    <td><%= user.weekly_exercise_target %></td>
    <td><%= user.smoke_total %></td>
    <td><%= user.weekly_drinks_target %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Food veg target:</b>
  <%= @user.food_veg_target %>
</p>

<p>
  <b>Food junk target:</b>
  <%= @user.food_junk_target %>
</p>

<p>
  <b>Hours sleep target:</b>
  <%= @user.hours_sleep_target %>
</p>

<p>
  <b>Weekly exercise target:</b>
  <%= @user.weekly_exercise_target %>
</p>

<p>
  <b>Smoke total:</b>
  <%= @user.smoke_total %>
</p>

<p>
  <b>Weekly drinks target:</b>
  <%= @user.weekly_drinks_target %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>